typography_spectrum: 0.8353343273047358
color:
  brandStrength: 0.055742347380146384
  lightness: 0.2284531109035015
  saturation: 0.776487679919228
  rhythmicContrast: 0.889047073200345
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.38989712740294635
name: The Office Interior Project Group®
title: >-
  The Office Interior Project Group® will design, build, furnish and support
  your workspace
description: Register now for pre-launch information and offers
